apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-todo-app
  labels:
    app: fastapi-todo
spec:
  replicas: 1                         # Number of pod replicas
  selector:
    matchLabels:
      app: fastapi-todo
  template:
    metadata:
      labels:
        app: fastapi-todo
    spec:
      containers:
      - name: fastapi-container
        image: shreyasingh21/fastapi-todo-app:latest   # Use your Docker image name and tag here
        ports:
        - containerPort: 8000            # Port that the FastAPI app is exposed on
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
